name: zephyr_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none
# Mininum sdk version



environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  flutter:
    sdk: flutter
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  flutter_bloc: ^8.1.2
  flutter_svg_provider: 
  google_sign_in: ^6.1.4
  cloud_firestore: ^4.4.5
  smooth_page_indicator:
  cached_network_image: 
  place_picker: ^0.10.0
  
  http: ^0.13.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0


dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0

flutter: 
  uses-material-design: true
  generate: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Manrope
      fonts: 
        - asset: assets/fonts/ManropeBold.ttf
          weight: 700
        - asset: assets/fonts/ManropeMedium.ttf
          weight: 500
