// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlFXfZNXaX_9I_Rls8ExqxkTu6OI1X3e0',
    appId: '1:281741773479:web:738d8db256f668e28c2982',
    messagingSenderId: '281741773479',
    projectId: 'zephyrapp-dev',
    authDomain: 'zephyrapp-dev.firebaseapp.com',
    storageBucket: 'zephyrapp-dev.appspot.com',
    measurementId: 'G-8FH2HX2SBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYWQnXJskQt9_sna4pu-uN3-vUVshFjb0',
    appId: '1:281741773479:android:8ba32acaa709f1de8c2982',
    messagingSenderId: '281741773479',
    projectId: 'zephyrapp-dev',
    storageBucket: 'zephyrapp-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtCrJct_R8EHKOqUt2xu6Dlwj2f0F0ANs',
    appId: '1:281741773479:ios:4ba9763406fb46d68c2982',
    messagingSenderId: '281741773479',
    projectId: 'zephyrapp-dev',
    storageBucket: 'zephyrapp-dev.appspot.com',
    androidClientId: '281741773479-9ru8jp0bjpgm2irf290a4t7s2nb368rq.apps.googleusercontent.com',
    iosClientId: '281741773479-1a7su7mq8bnigji4huff22982uun4hbb.apps.googleusercontent.com',
    iosBundleId: 'app.zephyrproject.zephyrapp',
  );
}
